### PR TITLE
Make 'Save' save to current file

### PR DESCRIPTION
**Pull request by blogscot**
Please have a look 🔎 and let me know what you think. 🤔

### CODE REVIEW

**Comment by sunilhari** [comment]
Hi @blogscot 

* Was using window.sessionStorage intentional instead of using window.localStorage due to which filename is not persisted.
*  The code that gets saved into file comes in a single line.

Not sure if this changes/Suggestions I mentioned are valid.

**Comment by heapwolf** [comment]
Since the code is persisted, I might also expect that if I edit the text again and save it, it would remember where to save it.

I'm seeing new-lines saved properly on macOS.

**Comment by blogscot** [comment]
Hi @sunihari 

To answer your first question. I debated whether it was a good idea to persist the _saved filename_ over a restart. If it was, it would be possible for a user to start working on something new (following a restart) and accidentally overwrite what they had previously been working by pressing CMD+S. The user could use SaveAs (SHIFT+CMD+S) instead, but more than likely users will forget - I know I wouldn't remember what I was doing the other day. By **not** persisting the _saved filename_ the user would be asked (once only) at the start of a new session to confirm where to save their work.

This is what I was thinking. Other choices are possible

Secondly, I'm not sure I understand - is there a problem with the file format?

**Comment by blogscot** [comment]
> Since the code is persisted, I might also expect that if I edit the text again and save it, it would remember where to save it.

Whatever you decide Paolo, but as I pointed out there is a potential gotcha when starting on new work following a restart.

**Comment by sunilhari** [comment]
@blogscot and  @0x00A 
2 point in my comment can be ignored.Now new lines are coming properly.Not sure what I did differently to find that issue

**Comment by sunilhari** [comment]
Clearing the filename would  not be possible if we  persist it .It would keep saving to the same file always.

**Comment by blogscot** [comment]
@sunilhari the user always has the (menu) option to **SaveAs** which would replace the stored filename.

**Comment by heapwolf** [comment]
> Whatever you decide Paolo, but as I pointed out there is a potential gotcha when starting on new work following a restart.

@blogscot good point! I think this is good to merge.

**Pull request merged**
