### PR TITLE
Issue#11

### PR DESCRIPTION
**Pull request by sunilhari**
Code had been refactored to fit in with master.Modified the regular expression that replaces it with line number.

### CODE REVIEW

**Comment by sunilhari** [comment]
Please review and accept

**Comment by sunilhari** [comment]
@0x00A : Please review my request.

**Comment by heapwolf** [comment]
Hey Hey, sorry I was really busy the last two weeks with travel. Just getting caught up now.

**Comment by sunilhari** [comment]
No Problem.Can we close that issue then??

**Pull request merged**
